/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoundEndRouteImport } from './routes/round-end'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as GameEndRouteImport } from './routes/game-end'
import { Route as GameRouteImport } from './routes/game'
import { Route as CreateRoomRouteImport } from './routes/create-room'
import { Route as IndexRouteImport } from './routes/index'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundEndRoute = RoundEndRouteImport.update({
  id: '/round-end',
  path: '/round-end',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const GameEndRoute = GameEndRouteImport.update({
  id: '/game-end',
  path: '/game-end',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoomRoute = CreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/game': typeof GameRoute
  '/game-end': typeof GameEndRoute
  '/lobby': typeof LobbyRoute
  '/round-end': typeof RoundEndRoute
  '/settings': typeof SettingsRoute
  '/tutorial': typeof TutorialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/game': typeof GameRoute
  '/game-end': typeof GameEndRoute
  '/lobby': typeof LobbyRoute
  '/round-end': typeof RoundEndRoute
  '/settings': typeof SettingsRoute
  '/tutorial': typeof TutorialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/game': typeof GameRoute
  '/game-end': typeof GameEndRoute
  '/lobby': typeof LobbyRoute
  '/round-end': typeof RoundEndRoute
  '/settings': typeof SettingsRoute
  '/tutorial': typeof TutorialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-room'
    | '/game'
    | '/game-end'
    | '/lobby'
    | '/round-end'
    | '/settings'
    | '/tutorial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-room'
    | '/game'
    | '/game-end'
    | '/lobby'
    | '/round-end'
    | '/settings'
    | '/tutorial'
  id:
    | '__root__'
    | '/'
    | '/create-room'
    | '/game'
    | '/game-end'
    | '/lobby'
    | '/round-end'
    | '/settings'
    | '/tutorial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoomRoute: typeof CreateRoomRoute
  GameRoute: typeof GameRoute
  GameEndRoute: typeof GameEndRoute
  LobbyRoute: typeof LobbyRoute
  RoundEndRoute: typeof RoundEndRoute
  SettingsRoute: typeof SettingsRoute
  TutorialRoute: typeof TutorialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/round-end': {
      id: '/round-end'
      path: '/round-end'
      fullPath: '/round-end'
      preLoaderRoute: typeof RoundEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-end': {
      id: '/game-end'
      path: '/game-end'
      fullPath: '/game-end'
      preLoaderRoute: typeof GameEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-room': {
      id: '/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof CreateRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoomRoute: CreateRoomRoute,
  GameRoute: GameRoute,
  GameEndRoute: GameEndRoute,
  LobbyRoute: LobbyRoute,
  RoundEndRoute: RoundEndRoute,
  SettingsRoute: SettingsRoute,
  TutorialRoute: TutorialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
